In [8]:
import torch

x = torch.empty(2,3)
x
torch.rand(2)
torch.zeros(2,5)
torch.ones(2,2, dtype=torch.float16)

x.size()
### Tensor is another way of saying arrays
y = torch.tensor([2.5, 0.1])
z = torch.rand(2,2)
x = torch.rand(2,2)
result = torch.add(x, z)
result


# Any function that ends with _ will do an implace operation 
print(f"z:{z} \n x: {x}")
z.add_(x)


z:tensor([[0.9667, 0.2276],
        [0.0650, 0.4702]]) 
 x: tensor([[0.1087, 0.4233],
        [0.1199, 0.2622]])


tensor([[1.0754, 0.6510],
        [0.1849, 0.7324]])

#### Slicing operation

In [13]:
x = torch.rand(5,3)

## Similar to the slicing in numpy
x[:, 0]
x[1,1]
x[1,1].item() ## This only work when you have only one item in the tensor


0.8879007697105408

#### Reshaping tensors

In [18]:
x = torch.rand(4,4)
x
x.view(16)
x.view(-1, 8)   ## Pytorch will predict a good shape to this
x.view(-1, 8).size()


torch.Size([2, 8])

#### Converting numpy arrays to tensors and vice versa

In [25]:
import numpy as np

a = torch.ones(5)
b = a.numpy() ## Care must be taken because if the tensor is on CPU instead of GPU, it will share the same memroy location with the numpy array. And changing one will tend to change the other
type(b)

a.add_(1)
a
b
## a and b were affected by the change because they point to the same location

#### Creating tensors from numpy array
a = np.ones(5)
b = torch.from_numpy(a) ### Same caution needs to be taken
b
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(4, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to("cpu")




tensor([[1.0754, 0.6510],
        [0.1849, 0.7324]])

In [27]:
### requires_grad set to True tells pytorch to calculate the gradient for this tensor during the optimization stage

x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)