#### Autograd
** Gradients are essential for model optimization
- How it can be used to calculate gradient

In [13]:
import torch

x = torch.randn(3, requires_grad=True)
x
y = x + 2
y

z = y * y * 2
z = z.mean()

z.backward()  ## This will compute gradient of z w.r.t x (dz/dx). This also didn't take any argument because z is a scalar

'''
if z is a vector
v = torch.teensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) # Before it will work
'''
print(x.grad) ## This is where the gradient is stored



tensor([2.3087, 3.3761, 4.2142])


In [16]:
## how to prevent the gradient from being tracked

### Options
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

with torch.no_grad():
    y = x + 2


weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad) ## This will produce incorrect gradient
    ##To solve this
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
