# Getting Familiar with Numpy

In [25]:
import numpy as np

# The Basics

In [26]:
a = np.array([1,2,3])
b = np.array([[3,2,5,6], [0,1,4,8]])

In [27]:
# Getting the dimensions
b.ndim
a.ndim

1

In [28]:
# Getting the shapes
a.shape
b.shape

(2, 4)

In [29]:
# Getting the type
a.dtype
b.dtype

dtype('int32')

In [30]:
# Getting the size
a.size
a.itemsize
a.nbytes # Total size

12

### Accessing / Changing specific elements, rows, columns, etc

In [31]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
b = np.array([[[1,2,3],[4,5,6]], [[8,9,10],[11,12,13]]])
a.size
a.itemsize
a.ndim
a.shape
a
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [32]:
# Get a speciic element [r, c]
a[0,5]
a[0, :]
a[:,2]
a[0, 1:6:2]

b[1,0,:]

array([ 8,  9, 10])

### Initializing Different Types of Arrays

In [33]:
# Alll 0s matrix (x, y)
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
# All ones matrix (x, y)
np.ones((10, 3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
# Any other number
np.full((2, 2), 30, dtype='float')
np.full(a.shape, 20)
np.full_like(a, 20) # another option


array([[20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20]])

In [36]:
# random decimal numbers
np.random.rand(4, 2)
np.random.random_sample(a.shape)


array([[0.74104051, 0.25621475, 0.52109035, 0.87246147, 0.58614658,
        0.21903516, 0.94859414],
       [0.82130203, 0.27941748, 0.9356641 , 0.34167062, 0.12927379,
        0.97561399, 0.83101002]])

In [37]:
# RAndom integer values
np.random.randint(5, 10, size=(3,3))

array([[8, 9, 6],
       [7, 6, 5],
       [9, 8, 5]])

In [38]:
# The Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
# Repeating  arrays
arr = np.array([[1,2,3]])
np.repeat(arr, repeats=3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# Exercise

In [40]:
a = np.ones((5,5))
a[1:4,1:4] = 0
a[2,2] = 9
print(a)
print("Woaw!!! I got it right")

#Another method
z = np.zeros((3,3))
z[1,1] = 9
a[1:-1, 1:-1] = z
print(a)
print("It worked out!")

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Woaw!!! I got it right
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
It worked out!


## Copying of arrays
##### Becareful when copying arrays!!1

In [41]:
a = np.array([1,2,3])
#b = a # Content change in one will affect the other
b = a.copy()
b[0] = 100
b

array([100,   2,   3])

## Mathematics Capabilities of Numpy

In [42]:
a = np.array([1,2,3,4])
print(a-2)
print(a+2)
print(a/2)
a *= 2
print(a ** 2)

# Take sine
np.cos(a)


[-1  0  1  2]
[3 4 5 6]
[0.5 1.  1.5 2. ]
[ 4 16 36 64]


array([-0.41614684, -0.65364362,  0.96017029, -0.14550003])

#### Linear Algebra

In [43]:
a = np.ones((2,3))
b = np.full((3,2), 2)

np.matmul(a,b)

c = np.identity(3)
np.linalg.det(c)


1.0

#### Statistics

In [44]:
stats = np.array([[1,2,3], [4,5,6]])
np.mean(stats)
np.min(stats, axis=1)
np.max(stats, axis=1)
np.sum(stats)


21

#### Reorganizing Arrays

In [45]:
before = np.array([[1,2,3,4], [5,6,7,8]])
before.shape

before.reshape((4,2))

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])
np.hstack([h1,h2,h1,h2])


array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous
###### Load Data from File

In [46]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata


FileNotFoundError: data.txt not found.

### Boolean Masking and Advanced Indexing

In [ ]:
filedata > 40
filedata[filedata > 50]

np.any(filedata > 50, axis=0)
((filedata > 40) & (filedata < 100))


### Finding an index of a particular element in an array

In [49]:
before = np.array([[1,2,3,4], [5,6,7,8]])
idx = np.argwhere(before==7)[0]
idx

array([1, 2], dtype=int64)

In [55]:
A = np.arange(100)

B = A[[3, 5, 6]]

B[0] = -4 # This change only affects B and not A because B is a copy rather than a view

B = A[A<40]
B = A[(A<40) & (A>30)]

### Difference between &, and
###### & :- use in arrays and 'and' used when both sides is a single object

B


array([31, 32, 33, 34, 35, 36, 37, 38, 39])